---
- name: Add backports.list
  ansible.builtin.template:
    src: debian.backports.list.j2
    dest: /etc/apt/sources.list.d/backports.list
    mode: '0640'
  when: enableBackports == "yes"

- name: Add backports preferences
  ansible.builtin.template:
    src: debian.backports.preferences.j2
    dest: /etc/apt/preferences.d/backports
    mode: '0640'
  when: enableBackports == "yes"

- name: Clean up backports settings
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
  - /etc/apt/sources.d/backports.list
  - /etc/apt/preferences.d/backports
  when: disableBackports == "yes"

