- name: Add kubernetes repository key to apt
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kubeVersion }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes.asc
    mode: '0644'

- name: Remove existing kubernetes repository file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent

- name: Add kubernetes repository to apt
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v{{ kubeVersion }}/deb/ /"
    state: present
    filename: kubernetes
