- name: Update master nodes
  delegate_to: "{{ master_node | split('.') | first }}"
  block:
  - name: Update kubelet and the rest
    ansible.builtin.apt:
      name: '*'
      update_cache: yes
      state: latest

  - name: Restart kubelet
    ansible.builtin.systemd:
      name: kubelet
      daemon_reload: yes
      state: restarted
      enabled: yes
