---

site: ""

kubeAPIFQDN: "example-k8s.example.cloud"
hostDomain: "{{ (kubeAPIFQDN| split('.', 1))[-1] }}"

kubeDomain:  "example.k8s"
kubeName: "{{ kubeDomain | replace('.','-') }}"

podCIDR: "172.30.0.0/16"
serviceCIDR: "172.20.0.0/20"

kubeAPIPort: 6443
podCIDRSubnetSize: 24

kubeVIPVersion: 1.0.0

ciliumVersion: 1.18.2
ciliumClusterID: 69

cluster_create: "no"
master_add: "no"
worker_add: "no"
node_reset: "no"

containerdSocket: unix:///run/containerd/containerd.sock

masterFiles:
- /etc/kubernetes/pki/secret.yaml
- /etc/kubernetes/admin.conf
